name: Build and deploy .NET Core application to Web App NetCoreManager
on:
  push:
    branches:
    - Develop
env:
  AZURE_WEBAPP_NAME: NetCoreManager
  AZURE_WEBAPP_PACKAGE_PATH: UserManagment/published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 5.0.x
  WORKING_DIRECTORY: UserManagment
  ASPNETCORE_ENVIRONMENT : Azure
  SQLAZURECONNSTR_ConnectionStrings: Server=tcp:${{ secrets.DBSERVER }},1433;Initial Catalog=Manager_db;Persist Security Info=False;User ID=${{ secrets.DBLOGIN }};Password=${{ secrets.DBPASSWORD }};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{secrets.TEST }} | sed 's/./& /g'
    - run: echo ${{secrets.TEST }}
    - run: echo ${{secrets.TEST2 }} | sed 's/./& /g'
    - run: echo ${{secrets.TEST2 }}
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Install dotnet-ef
      run: dotnet tool install --global dotnet-ef
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - run: dotnet-ef database update --project ${{ env.WORKING_DIRECTORY }}
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.NETCOREMANAGER_FFFF }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
